#cloud-config

write_files:
    - path: /etc/mongod.conf
      owner: root:root
      content: |
          storage:
            dbPath: /var/lib/mongodb
          #  engine:
          #  wiredTiger:

          # where to write logging data.
          systemLog:
            destination: file
            logAppend: true
            path: /var/log/mongodb/mongod.log

          # network interfaces
          net:
            port: 27017
            bindIp: 0.0.0.0

          # how the process runs
          processManagement:
            timeZoneInfo: /usr/share/zoneinfo
    - path: /opt/mongo-backup
      owner: root:root
      permissions: "0755"
      content: |
          #!/bin/bash
          backup_file=/opt/`date '+%s'`.tar
          mongodump --out=/opt/backup/mongodump-1
          tar -cvf $backup_file /opt/backup
          /snap/bin/gsutil cp $backup_file gs://tasky-mongo-backups
          rm $backup_file
    - path: /opt/mongo-admin
      owner: root:root
      permissions: "0755"
      content: |
          use admin
          db.createUser(
            {
              user: "admin",
              pwd: "password",
              roles: [ 
                { role: "userAdminAnyDatabase", db: "admin" },
                { role: "readWriteAnyDatabase", db: "admin" } 
              ]
            }
          )
    - path: /opt/enable-auth
      owner: root:root
      permissions: "0755"
      content: |
        security:
          authorization: enabled

runcmd:
    - curl -fsSL https://pgp.mongodb.com/server-7.0.asc |  sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
    - echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
    - sudo apt update
    - sudo apt install -o Dpkg::Options::="--force-confold" -y mongodb-org
    - sudo bash -c 'echo "*/2 * * * * root /opt/mongo-backup" >> /etc/crontab'
    - sudo systemctl start mongod
    - sleep 30
    - sudo mongosh < /opt/mongo-admin
    - sudo bash -c 'cat /opt/enable-auth >> /etc/mongod.conf'
    - sudo systemctl restart mongod
    
    
